---
title: "R Notebook"
output: html_notebook
---

1. Import libraries
```{r}
library(tidyr)
library(ggplot2)
library(gridExtra)
```

2. Functions
```{r}
#get evec and eval file
openfile <-function(filename, datapath){
  values_file = paste(datapath, filename, '.eval', sep='') #pca values
  vectors_file = paste( datapath,filename, '.evec', sep='') #table
  return( c(values_file, vectors_file))
}

#get pca labels
pcavals <- function(filename){
  values = read.table(filename, header= F)[,1]
  relval = values*100/sum(values)
  PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
  PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
  PC3 = paste('PC3 (', round(relval[3], 3),'%)', sep='')
  return( c(PC1, PC2, PC3))
}
```

3. Define colours (palette)
```{r}
#blue
blue = rgb(128, 156, 200, maxColorValue = 255)
blue1 = rgb(129, 156, 200, maxColorValue = 255)
#pink
pink = rgb(208, 146, 166, maxColorValue = 255)
#yellow
yell = rgb(236, 214, 052, maxColorValue = 255)
#orange
oran = rgb(244, 164, 072, maxColorValue = 255)
oran1 = rgb(244, 164, 073, maxColorValue = 255)
#purple
purp = rgb(175, 129, 192, maxColorValue = 255)
purp1 = rgb(175, 130, 192, maxColorValue = 255)
purp2 = rgb(175, 129, 191, maxColorValue = 255)
#green
gree = rgb(120, 208, 104, maxColorValue = 255)
gree1 = rgb(120, 208, 105, maxColorValue = 255)

dblue = rgb(032, 058, 123, maxColorValue = 255)
dgree = rgb(026, 139, 017, maxColorValue = 255)
dpink = rgb(139, 048, 088, maxColorValue = 255)
dyell = rgb(203, 151, 002, maxColorValue = 255)
doran = rgb(216, 082, 007, maxColorValue = 255)
dpurp = rgb(112, 042, 112, maxColorValue = 255)

#targed red
redd = rgb(216, 000, 047, maxColorValue = 255)
```


4. File list
```{r}
#set directory
datapath = '~\\masterBIOINFO\\practiques_tesis\\practiques\\data\\'
setwd(datapath)
dtp=''

#filenames
filename1 = 'mergeLAZ_FAGMER_PJL_comsnp_ld_pca'
filename2 = 'mergeLAZ_FAGMER_comsnp_ld_pca'
filename3 = 'mergeLAZ_FAGMER_comsnp_ld_eurwrussia_pca'
filename4 = 'mergeLAZ_FAGMER_comsnp_ld_eur_pca'
filename5 = 'mergeLAZ_FAGMER_comsnp_ld_eur_nofag_pca'
filename6 = 'mergeLAZ_FAGMER_comsnp_ld_spain_pca'
filename8 = 'iberianpeninsula_ids_nofr_pca'
filename7 ='mergeLAZ_FAGMER_comsnp_ld_spain_nocan_pca'
#store filenames
filenamelist = c(filename1, filename2, filename3, filename4, filename5, filename6,filename7, filename8,filename8)
#to store values file
values_filelist = c()
#to store vectors file
vectors_filelist = c()

for (file in filenamelist){
  filelist = openfile(file,datapath)
  values_filelist = c(values_filelist, filelist[1])
  vectors_filelist = c(vectors_filelist, filelist[2])
}
```


5. Group populations
```{r}
#first group colouts (with pjl, africa)
pjl= c("PJL")
africa = c("Algerian","Jew_Libyan","Jew_Moroccan","Jew_Tunisian","Libyan","Moroccan","Mozabite","Tunisian")
midleeast = c("Armenian", "Assyrian","Iranian", "Egyptian","Abkhasian", "Georgian","Jordanian", "Lebanese","Iranian_Bandari","Lebanese_Christian","Lebanese_Muslim","Druze", "Palestinian", "BedouinA", "BedouinB","Saudi","Syrian","Turkish","Jew_Turkish","Jew_Yemenite",  "Yemen","Jew_Georgian", "Jew_Iranian", "Jew_iraqi")
europe = c("Albanian","Greek","Bulgarian", "Croatian", "Estonian","Lithuanian","Ukrainian",  "Hungarian","Belarusian","Romanian", "Norwegian","Icelandic","Finnish", "Saami_WGA" , "Italian_South", "Cypriot", "Czech",    "Sicilian", "Jew_Ashkenazi", "Maltese","Italian_North", "English", "Scottish" , "Orcadian", "French", "Sardinian","Russian")
rusia = c( "Adygei", "Aleut",     "Aleut_Tlingit",  "Altaian","Balkar", "Chechen",   "Chukchi",   "Chuvash",  "Dolgan",   "Eskimo","Even",  "Ignore_Adygei(relative_of_HGDP01382)" ,"Itelmen", "Kalmyk","Koryak",    "Kumyk","Lezgin",   "Mansi", "Mordovian","Nganasan",  "Nogai","North_Ossetian", "Selkup", "Tuvinian","Ulchi", "Yakut","Tubalar", "Yukagir")
spain =c("Canary_Islander", "Basque", "Spanish", "Spanish_North", "FAG")
mer = c("MER")

#second (new) group colours (europe in soubgroups, turquia and russia)
europe2 = c("Norwegian","Icelandic","Finnish", "Saami_WGA" , "Italian_South", "Cypriot", "Czech",    "Sicilian", "Jew_Ashkenazi", "Maltese", "English", "Scottish" , "Orcadian",  "Sardinian")
easteur = c("Albanian","Greek","Bulgarian", "Croatian","Estonian","Lithuanian","Ukrainian",  "Hungarian","Belarusian","Romanian", "Russian")
turq = c("Turkish","Jew_Turkish")
french = c("French")
ndit = c("Italian_North")


#spaingroups
bas = c("Basque_Spanish","Spanish_Pais_Vasco_IBS")
cas_leon = c("Spanish_Castilla_y_Leon_IBS")   
cas_manc = c("Spanish_Castilla_la_Mancha_IBS")
ext = c("Spanish_Extremadura_IBS")
can = c("Spanish_Cantabria_IBS")
cat = c("Spanish_Cataluna_IBS")
val = c("Spanish_Valencia_IBS")
bal = c("Spanish_Baleares_IBS")
mur = c("Spanish_Murcia_IBS")         
and = c("Spanish_Andalucia_IBS")
ara = c("Spanish_Aragon_IBS")          
gal = c("Spanish_Galicia_IBS")            


### first group ###
cpops1_list = list(mer, spain, europe, rusia, midleeast, africa, pjl)
cpops1_name = c('Mercheros','Spain', 'Europe', 'Caucasus (Russia)','Middle East', 'Nord Africa',  'Punjabi')
cpops1_col = c(redd, purp, blue, pink, oran, gree, yell)
### second group ###
cpops2_list = list(mer, spain, french, ndit, easteur, europe2, rusia, turq)
cpops2_name = c('Mercheros','Spain','France', 'Nord Italy', 'East europe (balkans included)', 'Rest of Europe', 'Caucasus (Russia)','Turkey')
cpops2_col = c(redd, purp, gree, yell, dblue, blue, pink, oran)
### third group ###
cpops3_list = list(mer, cas_leon, cas_manc, ext, can, cat, val, bal, mur, and, ara, gal, bas)
cpops3_name = c("Mercheros", "Castilla y Leon","Castilla la Mancha","Extremadura", "Cantabria", "Catalunya", "Valencia", "Baleares", "Murcia", "Andalucia", "Aragon", "Galicia", "Basques")

cpops3_col = c(redd, purp, purp, purp, purp, purp, purp, purp, purp, purp, purp, purp, purp)
pops2pch2 = c(19,       1,1,          1,1,      1,    1,     1, 1,       1,      1,    1,     0)
#spain by autonomous comunity
cpops3_col3 = c(redd, blue, blue, gree, dblue, yell, oran, pink, oran, gree, yell, dblue, purp)
pops2pch3 = c(19,       10,1,          1,1,      1,    1,     10, 10,       10,      10,    10,     0)

#group pops lists
popslist = list (cpops1_list, cpops1_list, cpops2_list,cpops2_list, cpops2_list, cpops2_list, cpops2_list, cpops3_list, cpops3_list)
popscol = list (cpops1_col, cpops1_col, cpops2_col,cpops2_col, cpops2_col, cpops2_col, cpops2_col,cpops3_col,cpops3_col3)
clegend = list(cpops1_name,cpops1_name,cpops2_name, cpops2_name,cpops2_name, cpops2_name, cpops2_name,cpops3_name,cpops3_name)


#pch labels
basq = c("Basque" , "Spanish_North" , "Basque_Spanish","Spanish_Pais_Vasco_IBS")
jew = c("Jew_Ashkenazi","Jew_Georgian", "Jew_Iranian", "Jew_iraqi", "Jew_Libyan", "Jew_Moroccan", "Jew_Tunisian", "Jew_Turkish", "Jew_Yemenite")
roma = c('FAG', 'PJL') #PCH 25 triangle invertit
target = c('MER')#sumary + assgign colour
pops2 = list( target, '', basq, jew,  roma)
pops2pch = c(19,        1,0,      2,     6)
pchlabels = c("Mercheros", "", "basque", "jew",  "roma")


```


### PLOTING PCA'S###

1. Whole dataset with and without punjabi
```{r}
#whole subgroup 
n=1
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}

  #pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}

labels1 =c('Mercheros','Spain','Spanish Roma' , 'Basque','Europe','Ashkenazi Jews', 'Caucasus (Russia)','Middle East','Middle-Eastern Jews', 'Nord Africa','Nord-African Jews',  'Punjabi')
pchlab1 = c(19, 1,6,0,1,2,1,1,2,1,2,6)
collab2 =c(redd, purp, purp1, purp2, blue,blue1, pink, oran,oran1, gree,gree1, yell)


#plot
ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = collab2,
                        labels = labels1)+
  scale_continuous_identity(name = "Population",
                          breaks = pchlab1,
                          labels = labels1,
                          aesthetics = 'shape') 
  
  
#whitout punjabi 
n=2
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}
  #pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}

  #plot 
ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = c(redd, purp, purp, purp, blue,blue, pink, oran,oran, gree,gree, yell),
                        labels = c('Mercheros','Spain','Spanish Roma' , 'Spanish Basque','Europe','Ashkenazi Jews', 'Caucasus (Russia)','Middle East','Middle-Eastern Jews', 'Nord Africa','Nord-African Jews',  'Punjabi'))+
  scale_continuous_identity(name = "Population",
                          breaks = c(19, 1, 6, 0,1,2,1,1,2,1,2,6),
                          labels = c('Mercheros','Spain','Spanish Roma' , 'Basque','Europe','Ashkenazi Jews', 'Caucasus (Russia)','Middle East','Middle-Eastern Jews', 'Nord Africa','Nord-African Jews',  'Punjabi'),
                          aesthetics= 'shape')
  
  
```


2. subgroups, more focused on europe
```{r}
#without africa 
n=3
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}
  #pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}

labels1 =c('Mercheros','Spain','Spanish Roma', 'Basque','France', 'Nord Italy', 'East europe (balkans included)', 'Rest of Europe','Ashkenazi Jews', 'Caucasus (Russia)','Turkey', 'Turkey Jews')

pchlab1 = c(19,     1,    6,   0,       1,    1,   1,       1,  2,  1,   1,2)
collab1 =c(redd, purp, purp1, purp2, gree, yell, dblue, blue, blue, pink, oran, oran)
  #plot 
ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = collab1,
                        labels = labels1)+
  scale_continuous_identity(name = "Population",
                          breaks = pchlab1,
                          labels = labels1,
                          aesthetics= 'shape')


### without caucasus (russia)
n=4
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}
  #pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}
  #plot 
  ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = collab1,
                        labels = labels1)+
  scale_continuous_identity(name = "Population",
                          breaks = pchlab1,
                          labels = labels1,
                          aesthetics= 'shape')
 
   
# europe soubgroup + turkey
n=5
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}

#pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}

  ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = collab1,
                        labels = labels1)+
  scale_continuous_identity(name = "Population",
                          breaks = pchlab1,
                          labels = labels1,
                          aesthetics= 'shape')
  

  
  #spain, france, italy without canary islanders
  n=7 
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
  # Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
  }
}

#pch
for (i in 1:length(pops2)){
  subpop = pops2[[i]]
  for (j in subpop){
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch[i]
  }
}
#plot
  ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = collab1,
                        labels = labels1)+
  scale_continuous_identity(name = "Population",
                          breaks = pchlab1,
                          labels = labels1,
                          aesthetics= 'shape')
```

3. iberian peninsula subset 
```{r}
#spain
n=8
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
# Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch2[i]
  }
}

ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = popscol[[n]],
                        labels = cpops3_name)+
  scale_continuous_identity(name = "Population",
                          breaks = pops2pch2,
                          labels = cpops3_name,
                          aesthetics= 'shape')

n=9
vectors_tb = read.table(vectors_filelist[n], header= F)
vectors_tb=separate(vectors_tb, V1, c("pop", "id"), sep=":")
# Create new column filled with default colour & pch
vectors_tb$colour1="black"
vectors_tb$pch1= 1
    ##get pca labels
values = read.table(values_filelist[n], header= F)[,1]
relval = values*100/sum(values)
PC1 = paste('PC1 (', round(relval[1], 3),'%)', sep='')
PC2 = paste('PC2 (', round(relval[2], 3),'%)', sep='')
    ##get labels
pops = popslist[[n]]
colours = popscol[[n]]
    #colour
for (i in 1:length(pops)){
  subpop = pops[[i]]
  for (j in subpop){
    vectors_tb$colour1[vectors_tb$pop==j]=colours[i]
    vectors_tb$pch1[vectors_tb$pop==j]=pops2pch3[i]
  }
}


  #plot 
ggplot(data=vectors_tb, aes(x=V2,y=V3, color=colour1,shape=pch1)) +
  labs( x = PC1,  y= PC2)+
  geom_point() +
  scale_color_identity(name = "Population",
                       breaks = popscol[[n]],
                        labels = cpops3_name)+
  scale_continuous_identity(name = "Population",
                          breaks = pops2pch2,
                          labels = cpops3_name,
                          aesthetics= 'shape')



```





